config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :clients
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    paginates_per 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  before_action :authenticate_admin_user!
  private

    def client_params
      params.require(:client).permit(:name, :address, :phone)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  before_action :authenticate_admin_user!
  private

    def order_params
      params.require(:order).permit(:dateOrder, :quantity, :client_id, :product_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products= @q.result(distinct: true).page(params[:page]).order(:code)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:code, :description, :salesUnit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= client.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/home/index.html.erb
<br>
<h2 class="text-center">Tu apoyo a la Gestion de las pymes</h2>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Detalle Inventario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap vs 4.6-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous"
    />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <!-- Font Awesome 6.1.0 -->
    <script
      src="https://kit.fontawesome.com/6e8600afbc.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dateOrder, style: "display: block" %>
    <%= form.date_field :dateOrder %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Dateorder:</strong>
    <%= order.dateOrder %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order.quantity %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= order.client_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order.product_id %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid">
  <section id="Producto" class="bg-dark text-white d-none d-sm-block">
    <div>
      <h3 class="text-center pt-5 pb-3">Productos</h3>
      <hr class="opacity-100" />
    </div>

    <form>
      <div class="form-group">
        <%= form.label :code, style: "display: block" %>
        <%= form.text_field :code, html_options = { class: "form-control" } %>
        </div>
      <div class="form-group">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_field :description, html_options = { class: "form-control" }%>
      </div>
      <div class="form-group">
        <%= form.label :salesUnit, style: "display: block" %>
        <%= form.text_field :salesUnit, html_options = { class: "form-control" } %>
      </div>
      <%= form.submit %>

    <%# <button type="submit" class="btn btn-primary">Submit</button> %>
  </form>
  </section>
<% end %>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Code:</strong>
    <%= product.code %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Salesunit:</strong>
    <%= product.salesUnit %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Products</h1>

<%= search_form_for @q do |f| %>
<%= f.label :salesUnit_cont %>
<%= f.search_field :salesUnit_cont %>

<%= f.submit %>
<% end %>

<div id="products">
<table class="table table-border" width ="100%">
  <thead>
    <tr>
      <th>Código Prod</th>
      <th>Descr. Prod</th>
      <th>Unid.Vta</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr id="<%= dom_id product %>">
      <td> <%= product.code %></td>
      <td> <%= product.description %></td>
      <td> <%= product.salesUnit %></td>
      <td> <%= link_to "Edit this product", edit_product_path(product) %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<!-- Inicio Barra Navegador -->
<nav class="navbar navbar-expand-lg navbar-dark mx-4 bg-dark">
<button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
>
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link"%>
        <%# <a class="nav-link" href="#">Inicio </a> %>
    </li>
    <li class="nav-item">
        <%= link_to "Producto", products_path, class: "nav-link" %>
        
    </li>

    <li class="nav-item">
        <a class="nav-link" href="#Inventario">Inventario</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="#Ingreso">Ingreso</a>
    </li>
    <li class="nav-item">
        <%= link_to "Clients", clients_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Orders", orders_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Log In", admin_user_session_path, class: "nav-link" %>
    </li>
    </ul>
</div>
</nav>
<!-- Fin Barra Navegador -->